### ISSUE TITLE
[VIEW] Исправить ссылки на странице приветствия

### ISSUE THREAD

**Issue by anry-das** [EEM86/Gradebook#2]
При переходе со страницы приветствия по любой ссылке получаем ошибку о том, что страница не найдена. На остальных страницах вроде ОК.
Необходимо исправить ссылки.

**Comment by anry-das** [comment]
Имеется в виду страница http://localhost:7001/Gradebook (без слеша в конце)

**Comment by EEM86** [comment]
Fixes #2 [https://github.com/EEM86/Gradebook/commit/650f827d481993677da0faff15a7020cd9fb7d55](url)
