### ISSUE TITLE
[REFACTORING] Указание типа Generic

### ISSUE THREAD

**Issue by anry-das** [EEM86/Gradebook#21]
В выражениях
`List findAll();`
необходимо проставить тип
`List<T> findAll();`
и соответствующим образом изменить имплементации.

**Comment by anry-das** [comment]
посмотрели - тут все значительно сложнее
сейчас попытаюсь сформулировать...

**Comment by anry-das** [comment]
кроме
`List<T> findAll();`
в DAO используем тип

**Comment by EEM86** [comment]
https://github.com/EEM86/Gradebook/commit/e98c364de82ce9d0eb80b3db5752dd710b950cea
